name: crowdy

description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^1.10.24
  uuid: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - .env

  fonts:
    - family: Hermit
      fonts:
        - asset: fonts/Hermit-Regular.otf
        - asset: fonts/Hermit-Bold.otf
          weight: 800
